use extended Group instead of property
adafruit/Adafruit_CircuitPython_Display_Button pull request #23
Opened 2020-08-10 20:06 UTC by FoamyGuy

This is the beginning of a resolution for the issue raised by #22 .

I have done basic testing with a slightly modified simpletest and it seems to be working as intended so far. It does need some more thorough testing though. And the example scripts should be updated to use the the API without accessing `group` property. 

However in making these changes and testing them out I got to thinking about the ramifications a bit more. This change as it is now breaks any existing user code that uses the button since the `group` property will no longer exist. 

Maybe it would be good to provide backwards compatibility for some time by returning the correct thing from a `group` property along with printing a deprecation warning message? 

I will work on getting this tested more and updating the examples this week. I wanted to get this PR created to see if anyone else has thoughts about making this change and/or the deprecation considerations.

2020-08-10 22:00 UTC, tannewt commented
I think you could use a property to have `.group` return self and print a warning.

2020-08-12 02:51 UTC, FoamyGuy commented
I think this is ready to go now. I have added a `group` property that returns `self` and prints a warning. The example scripts have also been updated to use new API for adding the button to other Groups.

2020-08-12 15:17 UTC, tannewt requested changes
One more set of suggestions. I don't think the zeroes help going forwards.

2020-08-12 15:17 UTC, tannewt commented on adafruit_button.py
> +        self._label.y = 0 + self.height // 2
```suggestion
        self._label.x = (self.width - dims[2]) // 2
        self._label.y = self.height // 2
```

I think these zeroes will be confusing going forwards.

2020-08-12 15:17 UTC, tannewt commented on adafruit_button.py
> +                    0 + 2, 0 + 2, width - 2, height - 2, r=10, fill=self.outline_color
```suggestion
                    2, 2, width - 2, height - 2, r=10, fill=self.outline_color
```

2020-08-12 15:17 UTC, tannewt commented on adafruit_button.py
> +                    0 + 2, 0 + 2, width - 2, height - 2, fill=outline_color
```suggestion
                    2, 2, width - 2, height - 2, fill=outline_color
```

2020-08-13 04:09 UTC, FoamyGuy commented
Latest commit removes the usage of extra zeros in the calculations.

2020-08-13 18:53 UTC, tannewt approved these changes
Looks good! Thank you!

2020-08-13 18:53 UTC, merged